language: node_js
node_js:
 - "6"
notifications:
 email: false
services:
  - postgresql
cache:
 directories:
   - node_modules
before_script:
 - npm install
 - psql -c "create database testdb;" -U postgres
 - psql -c "create USER user WITH PASSWORD 'user';" -U postgres
 - sequelize db:migrate
 - sequelize db:seed:all

script:
 - npm run test
after_success:
#  - npm run coverage
#  - npm run report-coverage
#  - npm run coveralls
 - npm run coverage
 - npm run codeclimate-report
 - npm run check-coverage
env:
  #global:
 - NODE_ENV=test